name: Basic actions composition test
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # checkout the private repo containing the action to run
       - name: checkout private repo
         uses: actions/checkout@v2
         with: 
          repository: melscoop-test/composition-setup-test-private
          ref: v1
          token: '${{ secrets.GITHUB_TOKEN }}' # stored in GitHub secrets
          path: ./
          persist-credentials: false
          
       - name: Run Private Action
         uses: ./action.yml
         with:
           input1: value1
