name: Basic actions composition test
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # checkout the private repo containing the action to run
      - name: Checkout GitHub Action Repo
      - uses: actions/checkout@v2
      - uses: melscoop-test/composition-setup-test-private@main
        with: 
          token: '${{ secrets.GITHUB_TOKEN }}' # stored in GitHub secrets
      - name: Run the action
        uses: ./action.yml
