name: Basic actions composition test
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test some actions 
        uses: melscoop-test/composition-setup-test-private@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
