name: Basic actions composition test
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
     # checkout this repo
      - name: Checkout Repo
        uses: actions/checkout@v2
        # checkout the private repo containing the action to run
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with: 
          repository: melscoop-test/composition-setup-test-private
          ref: v1
          token: ${{ secrets.GITHUB_TOKEN }} # stored in GitHub secrets
      - name: Run the action
        uses: ./action.yml
