name: Basic actions composition test
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # checkout the private repo containing the action to run
       - uses: actions/checkout@v2
         with: 
          repository: melscoop-test/composition-setup-test-private
          token: '${{ secrets.GITHUB_TOKEN }}' # stored in GitHub secrets
       - uses: ./action.yml
